### ISSUE TITLE
As an Administrator I want to be able to Add/Edit/Remove the acceptable email domain.

### ISSUE THREAD

**Issue by joyep-jojo** [belatrix/BackendAllStars#116]

**Comment by neosergio** [comment]
We didn't have QA ;)

**Comment by joyep-jojo** [comment]
@neosergio , I told you two weeks ago =(

**Comment by neosergio** [comment]
My proposal is to use: 

```
EMAIL_DOMAIN_LIST = {
    'belatrixsf.com',
    'gmail.com',
}
```

So you can edit, add or remove any email domain. I will work in other improvement that we can completed deactivate email domain validation, but for now we can continue with development process using this email list in order to force validation.

**Comment by neosergio** [comment]
[Added](https://github.com/belatrix/BackendAllStars/commit/aa55f6d9f4cdabc23ee89039b197cff252869a9d)
