### ISSUE TITLE
Error response not following standard when trying to log in

### ISSUE THREAD

**Issue by gyosida** [belatrix/BackendAllStars#119]
The error response from api/employee/authenticate is returning as:
{"non_field_errors":["Unable to log in with provided credentials."]}

when it should be "detail" instead of "non_field_errors"

**Comment by neosergio** [comment]
[Fixed](https://github.com/belatrix/BackendAllStars/commit/5a17b5e1f2f03b44a50af856577bfa648eb23cb1).
