### ISSUE TITLE
[Urgent] Getting access to avatar denied in almost every API call

### ISSUE THREAD

**Issue by PedroCarrillo** [belatrix/BackendAllStars#132]
Calling .../api/employee/list/top/current_month_score/15/

throws: "detail":"Attempted access to '/media/avatar/allstar_user.jpg' denied."

<-- 500 Internal Server Error .../api/employee/list/top/current_month_score/15/ (609ms)
05-29 15:14:19.523 15971-16048/com.belatrixsf.allstars D/OkHttp: Connection: keep-alive
05-29 15:14:19.523 15971-16048/com.belatrixsf.allstars D/OkHttp: Server: gunicorn/19.4.5
05-29 15:14:19.523 15971-16048/com.belatrixsf.allstars D/OkHttp: Date: Sun, 29 May 2016 20:14:20 GMT
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: Transfer-Encoding: chunked
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: Vary: Cookie
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: Content-Type: application/json
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: X-Frame-Options: SAMEORIGIN
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: Allow: GET, OPTIONS
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: Via: 1.1 vegur
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: OkHttp-Sent-Millis: 1464552859204
05-29 15:14:19.524 15971-16048/com.belatrixsf.allstars D/OkHttp: OkHttp-Received-Millis: 1464552859523
05-29 15:14:19.525 15971-16048/com.belatrixsf.allstars D/OkHttp: {"detail":"Attempted access to '/media/avatar/allstar_user.jpg' denied."}

**Comment by neosergio** [comment]
Fixed
