### ISSUE TITLE
Users without recommendations shouldn't appear on Ranking

### ISSUE THREAD

**Issue by Gladislao** [belatrix/BackendAllStars#168]
Expected.
Users that haven't received any recommendations shouldn't be displayed on the ranking list. 

Actual.
Users without recommendations are being displayed on the ranking list

**Comment by neosergio** [comment]
In progress 👍

**Comment by neosergio** [comment]
Fixed: https://github.com/belatrix/BackendAllStars/commit/68ff61bfe177ce542f9c4131f3da228a6f7ed9a6
