### ISSUE TITLE
A message should be displayed when the ranking list is empty

### ISSUE THREAD

**Issue by Gladislao** [belatrix/BackendAllStars#169]
Actual result.
A list of users without recommendations appear on the ranking list

Expected result.
A message should be displayed when there aren't any user with a recommendation.

**Comment by neosergio** [comment]
Actual result is not accurate, please add more details 👍

**Comment by neosergio** [comment]
Fixed even reporter confused actual result (@Gladislao 😝 ) https://github.com/belatrix/BackendAllStars/commit/d66fdf55b4888bf8d95963b1d904605c69485c5c
