### ISSUE TITLE
Build /api/stars/{employee_id}/subcategory/list/

### ISSUE THREAD

**Issue by jesvalag** [belatrix/BackendAllStars#19]
Follow [/api/stars/{employee_id}/subcategory/list/](https://github.com/belatrix/BackendAllStars/wiki#apistarsemployee_idsubcategorylist) endpoint documentation

**Comment by jesvalag** [comment]
Follow [/api/stars/{employee_id}/subcategory/list/](https://github.com/belatrix/BackendAllStars/wiki#apistarsemployee_idsubcategorylist) endpoint documentation

**Comment by neosergio** [comment]
[Merged](https://github.com/belatrix/BackendAllStars/pull/26)
