### ISSUE TITLE
Build /api/employee/{employee_id}/category/list

### ISSUE THREAD

**Issue by neosergio** [belatrix/BackendAllStars#2]
Follow [/api/employee/{employee_id}/category/list](https://github.com/belatrix/BackendAllStars/wiki#apiemployeeemployee_idcategorylist) endpoint documentation.

**Comment by jesvalag** [comment]
Adding endpoint to get all the categories associated to a specific employee.

**Comment by neosergio** [comment]
[Merged](https://github.com/belatrix/BackendAllStars/pull/13)
