### ISSUE TITLE
Build /api/stars/{employee_id}/subcategory/{subcategory_id}/list/

### ISSUE THREAD

**Issue by jesvalag** [belatrix/BackendAllStars#20]

**Comment by jesvalag** [comment]
Follow [/api/stars/{employee_id}/subcategory/{subcategory_id}/list/](https://github.com/belatrix/BackendAllStars/wiki#apistarsemployee_idsubcategorysubcategory_idlist) endpoint documentation

**Comment by neosergio** [comment]
[Merged](https://github.com/belatrix/BackendAllStars/pull/29)
