### ISSUE TITLE
Bug: role coming as integer in GET /api/employee/{employee_id}/ 

### ISSUE THREAD

**Issue by gyosida** [belatrix/BackendAllStars#34]
JSON Response:

{"pk":2,"username":"pedro","email":"thisisemail@asdasd.com","first_name":"Pedro","last_name":"Carrillo","role":2,"skype_id":"1234","last_month_score":0,"current_month_score":0,"level":0,"score":0,"is_active":true,"last_login":"2016-04-21T16:26:25Z"}

**In console the user "pedro" has the following role "Senior Android Developer" but client is receiving the integer 2**

**Comment by neosergio** [comment]
Also categories is missing and it is needed for give stars to other employees

**Comment by neosergio** [comment]
[Fixed](https://github.com/belatrix/BackendAllStars/commit/879ea9c4234a5d8435f213c6f9b082a86a794ecc) and published
