### ISSUE TITLE
Can recommend to myself

### ISSUE THREAD

**Issue by PedroCarrillo** [belatrix/BackendAllStars#49]
As Search and Employee API's return myself, i can go in and give a recommendation. I think is a lot of work for a mobile device to filter this out.
One solutiion could be take the user from the authorization token? or just ask me my id in the service call.

keep me updated 👍

**Comment by neosergio** [comment]
[Fixed](https://github.com/belatrix/BackendAllStars/commit/2318f70dba15cac8d5e6368cef4efb1584499487) and published
