### ISSUE TITLE
difference between endpoints

### ISSUE THREAD

**Issue by PedroCarrillo** [belatrix/BackendAllStars#52]
GET /api/category/{category_id}/subcategory/list/  and  GET /api/star/{employee_id}/subcategory/list/

They return different keys for the same object. Please mobile needs them to be the same key.

**Comment by PedroCarrillo** [comment]
this is priority US PRESIDENT halcon alpha level ultra super archi urgent

**Comment by neosergio** [comment]
[Fixed](https://github.com/belatrix/BackendAllStars/commit/232f2961d8ff26f7263df5ab59c8b36ac8bd9b43) and published
