### ISSUE TITLE
Build /api/employee/{employee_id}/reset/password/

### ISSUE THREAD

**Issue by jesvalag** [belatrix/BackendAllStars#60]
Follow [/api/employee/{employee_id}/reset/password/](https://github.com/belatrix/BackendAllStars/wiki#apiemployeeemployee_idresetpassword) endpoint documentation

**Comment by neosergio** [comment]
I will work on this endpoint, and I will add more endpoints to handle users flow.

**Comment by neosergio** [comment]
There is a [unresolved bug](https://github.com/marcgibbons/django-rest-swagger/issues/303) in Django Swagger, so authentication flow probably won't be available through /api/docs/

**Comment by neosergio** [comment]
The proposal is to implement this endpoint POST /api/auth/password/ using djoser.

**Comment by neosergio** [comment]
Implemented, see documentation: https://github.com/belatrix/BackendAllStars/wiki#apiauthpassword
