### ISSUE TITLE
GET /api/employee/list/top/{kind}/{quantity}/ should returns one standard field with score value

### ISSUE THREAD

**Issue by neosergio** [belatrix/BackendAllStars#62]
In order to standardize response from top lists, we should use just score field value

**Comment by neosergio** [comment]
We will probably consider also years score (last and current)

**Comment by neosergio** [comment]
This is the proposal https://github.com/belatrix/BackendAllStars/commit/df6407d061e7a4f53021511c9c38593496e165a3

**Comment by PedroCarrillo** [comment]
does this means you are adding total_score to the employee entity?

**Comment by neosergio** [comment]
That's correct, I need to discuss with other team members. I'll confirm you after that discussion.

**Comment by neosergio** [comment]
[Added](https://github.com/belatrix/BackendAllStars/commit/df6407d061e7a4f53021511c9c38593496e165a3). We will publish on Heroku on May 04.
