### ISSUE TITLE
Events manager

### ISSUE THREAD

**Issue by neosergio** [belatrix/BackendAllStars#71]
This ticket should include models and initial serializers

**Comment by intiamaru** [comment]
Hi @neosergio , environment set up, I see there is models for events and talks. The scope of this task will be to generate an api for those? or which is the exact work we should do here. Thx

**Comment by neosergio** [comment]
Yes @jboneu , you should create endpoints just for events, Event list sorted by -date (GET), Event Detail (GET).

**Comment by intiamaru** [comment]
Hi @neosergio pull request of simple listing done, please let me know if something else necesary in procedure. And what else is needed in terms of the requirement.

**Comment by neosergio** [comment]
Thank you @jboneu, I will review and merge your pull request after this friday demo, when we closed 1.3 version.

**Comment by neosergio** [comment]
[Merged ](https://github.com/belatrix/BackendAllStars/pull/136)

**Comment by neosergio** [comment]
BUG: https://github.com/belatrix/BackendAllStars/issues/143

**Comment by neosergio** [comment]
BUG: https://github.com/belatrix/BackendAllStars/issues/142
