### ISSUE TITLE
Cannot post stars

### ISSUE THREAD

**Issue by joyep-jojo** [belatrix/BackendAllStars#73]
Cannot post stars using POST /api/star/{from_employee_id}/give/star/to/{to_employee_id}/

Response Body
Server Error (500)

Response Code
500 Internal Server Error

Response Headers
{
  "Date": "Tue, 03 May 2016 17:40:53 GMT",
  "Via": "1.1 vegur",
  "Server": "gunicorn/19.4.5",
  "X-Frame-Options": "SAMEORIGIN",
  "Vary": "Cookie",
  "Content-Type": "text/html",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Expose-Headers": "Access-Control-Allow-Origin, Access-Control-Allow-Headers",
  "Transfer-Encoding": "chunked",
  "Connection": "keep-alive"
}

**Comment by neosergio** [comment]
Fixed and published
