### ISSUE TITLE
Know when an user needs to reset password

### ISSUE THREAD

**Issue by PedroCarrillo** [belatrix/BackendAllStars#97]
For mobile, we need to know when the user is needed to be redirected to the Reset Password screen.

**Comment by neosergio** [comment]
[Refactored previous flow](https://github.com/belatrix/BackendAllStars/commit/56abc402a59b2fcf3d585c0ec120bd2b92d1068f) and [added](https://github.com/belatrix/BackendAllStars/commit/2e111856365b5311230d528942cc1cd25f6c2112) reset_password_code to serializer
