### ISSUE TITLE
api/employee/list/?search="dd dd"

### ISSUE THREAD

**Issue by KenyiRodriguez** [belatrix/BackendAllStars#99]
El servicio no busca correctamente la combinación de nombre y apellido.

**Comment by neosergio** [comment]
Search functionality is now separated by username, first_name and last_name so it is n't possible for now to combine first_name and last_name fields. However a fix proposal could be to split search terms if there are whitespaces and continue with query separated by mentioned fields above. I'll try to fix it ASAP but I'm not sure if I can get it by the end of v1.1 milestone this friday. I'll work on it

**Comment by neosergio** [comment]
This commit: https://github.com/belatrix/BackendAllStars/commit/e2cf9dff879a5e5a338b8c73f0457ca856c6d78f is the proposal, I need to run some tests with 100 employees or more but it is working now for 21 employees from sample data

**Comment by neosergio** [comment]
Refactor search algorithm [was improved](https://github.com/belatrix/BackendAllStars/commit/be309b87a461f1461a4677c1618b6a85f956ab08), thanks to @yraulr and @Gladislao
